changelog:
  exclude:
    labels:
      - tidy
      - merge-up
    authors:
      - mongodb-php-bot
      - mongodb-drivers-pr-bot[bot]
      - dependabot[bot]
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Security
      labels:
        - security
    - title: New Features
      labels:
        - feature
    - title: Fixed
      labels:
        - bug
    - title: Minor
      labels:
        - minor
    - title: Other Changes
      labels:
        - '*'
