name: Atlas CI

on:
  push:
    branches:
      - '[0-9]+.[0-9x]+'
  pull_request:
    branches:
      - '[0-9]+.[0-9x]+'
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    name: PHP/${{ matrix.php }} Laravel/${{ matrix.laravel }} Driver/${{ matrix.driver }}

    strategy:
      matrix:
        php: ['8.2', '8.3', '8.4', '8.5']
        laravel: ['12.*', '13.*']
        driver: [2]
        include:
          - php: '8.4'
            laravel: 12.*
            driver: 1
        exclude:
          - laravel: '13.*'
            php: '8.2'

    steps:
      - uses: actions/checkout@v7

      - name: Create MongoDB Atlas Local
        timeout-minutes: 5
        run: |
          docker run --name mongodb -p 27017:27017 --detach mongodb/mongodb-atlas-local:latest
          until docker exec --tty mongodb mongosh --eval "db.hello().isWritablePrimary" | grep -q true; do sleep 1; done
          until docker exec --tty mongodb mongosh --eval "db.getCollection('connection_test').insertOne({})"; do sleep 1; done
          until docker exec --tty mongodb mongosh --eval "db.getCollection('connection_test').createSearchIndex({mappings:{dynamic: true}})"; do sleep 1; done
          docker exec --tty mongodb mongosh --eval "db.getCollection('connection_test').drop()"
          until docker exec --tty mongodb mongosh --eval "db.runCommand({ serverStatus: 1 })"; do sleep 1; done

      - name: Setup PHP with MongoDB extension
        uses: ./.github/actions/setup-php
        with:
          php-version: ${{ matrix.php }}
          driver: ${{ matrix.driver }}
          extensions: curl,mbstring,xdebug
          coverage: xdebug

      - name: Show Docker version
        if: ${{ runner.debug }}
        run: docker version && env

      - name: Restrict Laravel version
        run: composer require --dev --no-update 'laravel/framework:${{ matrix.laravel }}'

      - name: Download Composer cache dependencies from cache
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v6
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ matrix.os }}-composer-

      - name: Install dependencies
        run: |
          composer update --no-interaction

      - name: Run tests
        run: |
          export MONGODB_URI="mongodb://127.0.0.1:27017/?directConnection=true"
          php -d zend.assertions=1 ./vendor/bin/phpunit --coverage-clover coverage.xml --group atlas-search
