name: Merge up

on:
  push:
    branches:
      - '[0-9]+.[0-9x]+'

jobs:
  merge-up:
    name: Create merge up pull request
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        id: checkout
        uses: mongodb-labs/drivers-github-tools/secure-checkout@v3
        with:
          app_id: ${{ vars.PR_APP_ID }}
          private_key: ${{ secrets.PR_APP_PRIVATE_KEY }}
          submodules: true
          fetch-depth: 0

      - name: Create pull request
        id: create-pull-request
        uses: alcaeus/automatic-merge-up-action@main
        with:
          ref: ${{ github.ref_name }}
          branchNamePattern: '<major>.<minor>'
          devBranchNamePattern: '<major>.x'
          enableAutoMerge: true
