name: "Static Analysis"

on:
  push:
    branches:
      - "[0-9]+.[0-9x]+"
  pull_request:
    branches:
      - "[0-9]+.[0-9x]+"
      - "feature/*"
  workflow_call:
    inputs:
      ref:
        description: "The git ref to check"
        type: string
        required: true

env:
  PHP_VERSION: "8.5"
  DRIVER_VERSION: "stable"
  MONGODB_EXT_V1: mongodb-1.21.0
  MONGODB_EXT_V2: mongodb-mongodb/mongo-php-driver@v2.x

jobs:
  phpstan:
    name: "PHP/${{ matrix.php }} Driver/${{ matrix.driver }}"
    runs-on: "ubuntu-22.04"
    continue-on-error: true
    strategy:
      matrix:
        php:
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'
        driver:
          - 2
        include:
          - php: "8.4"
            driver: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.ref || github.ref }}

      - name: "Get SHA hash of checked out ref"
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo CHECKED_OUT_SHA=$(git rev-parse HEAD) >> $GITHUB_ENV

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ matrix.driver == 1 && env.MONGODB_EXT_V1 || env.MONGODB_EXT_V2 }}
          key: "extcache-v1"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: "curl,mbstring,${{ matrix.driver == 1 && env.MONGODB_EXT_V1 || env.MONGODB_EXT_V2 }}"
          tools: composer:v2
          coverage: none

      - name: Cache dependencies
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: ./vendor
          key: composer-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        run: composer install

      - name: Restore cache PHPStan results
        id: phpstan-cache-restore
        uses: actions/cache/restore@v4
        with:
          path: .cache
          key: "phpstan-result-cache-${{ matrix.php }}-${{ github.run_id }}"
          restore-keys: |
            phpstan-result-cache-

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --no-interaction --no-progress --ansi --error-format=sarif > phpstan.sarif
        continue-on-error: true

      - name: "Upload SARIF report"
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: "github/codeql-action/upload-sarif@v4"
        with:
          sarif_file: phpstan.sarif

      - name: "Upload SARIF report"
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: "github/codeql-action/upload-sarif@v4"
        with:
          sarif_file: phpstan.sarif
          ref: ${{ inputs.ref }}
          sha: ${{ env.CHECKED_OUT_SHA }}

      - name: Save cache PHPStan results
        id: phpstan-cache-save
        if: always()
        uses: actions/cache/save@v4
        with:
          path: .cache
          key: ${{ steps.phpstan-cache-restore.outputs.cache-primary-key }}
